# Generated by Django 3.0.2 on 2020-05-23 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornavn', models.CharField(blank=True, max_length=200, null=True)),
                ('etternavn', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('bruker', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordrenr', models.CharField(blank=True, max_length=200, null=True)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('kunde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebutikk.Kunde')),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(blank=True, max_length=200, null=True)),
                ('pris', models.FloatField()),
                ('bilde', models.ImageField(default='def_bilde.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OrderElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antall', models.IntegerField(blank=True, default=1, null=True)),
                ('lagt_til', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebutikk.Order')),
                ('produkt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebutikk.Produkt')),
            ],
        ),
        migrations.CreateModel(
            name='Leveringsadresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('by', models.CharField(blank=True, max_length=200, null=True)),
                ('fylke', models.CharField(blank=True, max_length=200, null=True)),
                ('postnr', models.CharField(blank=True, max_length=200, null=True)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('kunde', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebutikk.Kunde')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebutikk.Order')),
            ],
        ),
    ]
