# Generated by Django 3.0.2 on 2020-05-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebutikk', '0002_auto_20200527_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='digital',
            field=models.BooleanField(default=False),
        ),
    ]
