# Generated by Django 3.0.2 on 2020-05-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebutikk', '0003_auto_20200529_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
